### ISSUE TITLE
Think of good way to tell recommendations

### ISSUE THREAD

**Issue by nielsrolf** [caTUstrophy/backend#104]
I think currently, when you create a matching from frontend, you first select a request or offer and then choose from a list of all offers/requests of the same region. It would be good if the frontend would ask for possible matching partners for one item, so that we can add a simple recommended flag to each item in the response (eg `GET regions/:ID/recommendations/:itemid`). Additionally we could add another endpoint where the admin can quckly get an overview for all recommendations, eg `Get regions/:ID/recommendations`.

**Comment by numbleroot** [comment]
We implemented exactly that in one of the last commits.
