### ISSUE TITLE
Technology discussion thread

### ISSUE THREAD

**Issue by numbleroot** [caTUstrophy/backend#13]
I would like to open this issue as a discussion thread for technologic choices we have to make during development.

Open questions and technology stack decisions:
1. What about a Redis instance handling the `userID -> JWT access token` mapping needed in every authorized request against our API? This would give us two things: 1) one less database call as we would not need to check a dedicated `UserSession` table; 2) hopefully a small performance boost compared to accessing the database as Redis is supposed to be a fast key-value store.
2. We need to be able to send mail with go. How do we want to approach that?
3. Do we need an additional testing framework additionally to the one go provides on its own?
4. Almost certainly, we will be dealing with maps and maps interfacing. Which map provider do we want to use? What are possible API limits this provider imposes? Is there a well established JavaScript or go library to access it? Ideas: OpenStreetMaps, Leaflet, Google Maps
5. How do we want to separate services? Docker them possibly on the same machine or make use of the to-be-provided OpenStack installation and spin up two to three dedicated virtual machines?
6. What are possible attack scenarios we did not consider yet and how are we able to prevent them?

**Comment by numbleroot** [comment]
For all decisions we have to make on libraries I encourage you to check out the curated [awesome-go](https://github.com/avelino/awesome-go) list.
1. Scratch Redis - we are going in-memory! :) Though Redis seems to be fantastic software it will probably be enough for us to use a go-in-memory-store for mapping `userIDs -> JWT`, like the [go-cache](https://github.com/patrickmn/go-cache) library. This will mean that all JWTs are gone if we restart the service but I think that is acceptable. At the same time it is one less network call we have to perform.
2. One of [these](https://github.com/avelino/awesome-go#email) will probably fit our needs from backend side.

**Comment by nielsrolf** [comment]
To 1.: I think redis is not necessary if we accept that users have to login again in case our server should crash. For the moment, I simply used maps to save the jwts.

**Comment by nielsrolf** [comment]
To 6.) I think if we already think about it, we can write curl requests and save them as bash scripts so that we have tests

**Comment by numbleroot** [comment]
To 6.) If you wanted to use your proposed workflow as a means of testing our implementation, I think we should not do that but rather use Go's built-in testing functionality or have a look at one of the many full-fledged Go testing frameworks. If you described an attack in your comment above, I don't fully understand it, sorry.

**Comment by numbleroot** [comment]
Do we want to gzip responses? This could primarily be useful for very verbose and expressive JSON responses. We could use a readily available middleware like [gziphandler](https://github.com/NYTimes/gziphandler) or do it by ourselves with the [compress/gzip](https://golang.org/pkg/compress/gzip/).

**Comment by numbleroot** [comment]
Concerning NLP techniques for calculating match scores:
A common algorithm used in Information Retrieval Systems appears to be the [term frequency - inverse document frequency](https://en.wikipedia.org/wiki/Tf%E2%80%93idf) (short: tf-idf) algorithm. Based on created tf-idf vectors, one can then go ahead and compute the [cosine similarity](https://en.wikipedia.org/wiki/Cosine_similarity) between two of those vectors. We could use these as the [0, 1] indicator for pair-wise similarity between an offer's and a request's description fields.

**Comment by numbleroot** [comment]
Coming close to the deadline of our last sprint, this issue is probably done. Very informative, still, for the future but nonetheless done.
