### ISSUE TITLE
API definition and soft-freeze for MVP

### ISSUE THREAD

**Issue by numbleroot** [caTUstrophy/backend#14]
Take part in defining the API so that we are able to soft-freeze it for our MVP. The current API status can be found [here](https://github.com/caTUstrophy/backend#api-documentation). At this point there are still a lot of endpoints which need to be defined initially. Focus on the ones tagged with API version "MVP".

**Comment by numbleroot** [comment]
@caTUstrophy/frontend team should be working on this, too. Also, GitHub team mention test. Working :)

**Comment by neopostmodern** [comment]
I think types are much more useful than explanations in the JSON-style payload definitions. The keys should be self-explanatory anyway. Proposing #15

**Comment by numbleroot** [comment]
Valid point, merged. Although this should be done for all endpoint definitions. Soon to be.

**Comment by nielsrolf** [comment]
Do we have to add GET/users again? If so, we should set #11 back to in progress or directly add it

**Comment by numbleroot** [comment]
In my opinion, `GET /users` is not needed for MVP but definitely afterwards. I certainly don't object to adding it now, we can implement it along the way.

**Comment by numbleroot** [comment]
I think, after Niel's commit 5e427263f2163f8ba99841da9811e716495045c6 today, we have quite extensive API documentation. All endpoints to be considered for MVP are well-defined. Closing.
