### ISSUE TITLE
Switch to ISO Dates

### ISSUE THREAD

**Issue by neopostmodern** [caTUstrophy/backend#19]
Could we switch to ISO dates? 

``` js
new Date().toISOString() == "2016-05-31T08:06:31.607Z";
```

They are easier to debug and definitely more self-contained (no need to worry about the attached unit). Bonus, they deal with time-zones. (See that "Z" in the end.) In JSON the size-difference is negligible.

**Comment by numbleroot** [comment]
This is going to take place in API v2.0.
