### ISSUE TITLE
JSON response clean up for all Creates and all users

### ISSUE THREAD

**Issue by nielsrolf** [caTUstrophy/backend#24]
Whenever we return user data via JSON, we send empty "PasswordHash" fields (and some more). Remove them.
Whenever we return create data, we send stuff we want to keep for ourselves like CreatedAt. Remove this. Maybe we need wrapper  return functions and structs that are made to contain only the information we want to send (not our intern structs)

**Comment by numbleroot** [comment]
`CreatedAt`, `UpdatedAt` and `DeletedAt` are gone because I replaced the default `gorm.Model` with only an UUID.
