### ISSUE TITLE
JWTs are undocumented, should provide ISO date (not relative time in milliseconds)

### ISSUE THREAD

**Issue by neopostmodern** [caTUstrophy/backend#26]
JWTs should be documented in the API page.
They should provide the **absolute** time they expire, as an ISO date. (Because: Why milliseconds? Why relative to server time? ISO for the win!)

**Comment by numbleroot** [comment]
[Stay tuned.](https://github.com/caTUstrophy/backend#what-is-inside-a-jwt)

**Comment by numbleroot** [comment]
[See here](https://github.com/caTUstrophy/backend#what-is-inside-a-jwt).
If that is what you had in mind, I would close this issue (see last commit).

**Comment by neopostmodern** [comment]
Yeah, works: https://github.com/caTUstrophy/frontend/commit/fca0d00613f73181935bb42f22bd7e9d72eca9ad
