### ISSUE TITLE
Decide how to handly polygons

### ISSUE THREAD

**Issue by nielsrolf** [caTUstrophy/backend#31]
Probably postgis
How do we want to develop on localhost?
- Interface everything that uses Posgis and write everything that uses INTERSEVT twice, with a sqlite version and a postgis version
- Install Postgres and Postgis on our local systems
- Find a sqlite extension that has the same interface as postgis

**Comment by numbleroot** [comment]
I think, we agreed upon installing Postgres and PostGIS locally as there seem to be no viable alternatives for SQLite. On production, the setup Postgres + PostGIS is needed anyways.

**Comment by numbleroot** [comment]
Yes, the above mentioned way will be the path we are following.
Closing this due to the made decision.
