### ISSUE TITLE
Getting single offers, requests, matchings, areas

### ISSUE THREAD

**Issue by neopostmodern** [caTUstrophy/backend#47]
It would make sense (or probably be necessary) to have a possibility to get a single entity for every collection.
The idiomatic way of doing this would obviously be

```
GET /entity/:id
```

where `entity` is one of offers, requests, matchings or areas and `:id` is a UUID.

This would conflict with the current `GET offers/:area` but it doesn't look like that would work for us anyway.

**Comment by numbleroot** [comment]
We discussed this in our jit.si call today. The structure of the API changed quite significantly to reflect these changes.
