### ISSUE TITLE
User trust system

### ISSUE THREAD

**Issue by nielsrolf** [caTUstrophy/backend#66]
Create a user trust system:
A new region shall get a flag "not confirmed". If many users or one user with a high trust value confirmt, the region shall be confirmed. Users can  increase their trust values  eg by rated offers. Also, an admin could set trust values

**Comment by numbleroot** [comment]
As per this sprint planning, we agreed on not doing this. It still is an interesting and in our opinion useful idea, but we will focus on an interesting matching algorithm instead.
