### ISSUE TITLE
Create User behaves strange

### ISSUE THREAD

**Issue by nielsrolf** [caTUstrophy/backend#78]
The following request to POST /users fails unexpectedly:

Request:

```
{
    "Name": "Alexandra Maria Namia",
    "PreferredName": "alex",
    "Mail": "alexandra1.m.namia@example.com",
    "PhoneNumbers": [
        "012012312373",
    ],
    "Password": "WhyNotSafe1337Worlds?"
}
```

```
Response:
{"Error":"Supplied values in JSON body could not be parsed"}
```

**Comment by numbleroot** [comment]
You receive that response because the supplied JSON is invalid. The phone number in the `PhoneNumbers` array should not have a trailing comma after it.

Works without the comma.
