### ISSUE TITLE
permission/CheckScope not used everywhere

### ISSUE THREAD

**Issue by jeichelbaum** [caTUstrophy/backend#92]

**Comment by jeichelbaum** [comment]
eg. CreateRegion can be done by anyone, create region with global size boundaries results in global admin access

**Comment by nielsrolf** [comment]
The creator of a region is not automatically its admin. Maybe instead of this, a system admin should confirm a region and regions get a flag for this?

**Comment by nielsrolf** [comment]
One way would be: we add a confirmed flag to regions which is set to true if the author is a system admin. Otherwise, the flag defaults to false. A region that is created by a user can be updated with the usual put /regions/:regionID.

**Comment by jeichelbaum** [comment]
Error was on my end I didnt realize everybody is allowed to create regions

**Comment by jeichelbaum** [comment]
But after writing some tests it seems like normal users can create matchings without superadmin / region admin status
