### ISSUE TITLE
Implement a matching score algorithm

### ISSUE THREAD

**Issue by numbleroot** [caTUstrophy/backend#96]
In order to provide our region admins a means to decide which request is best to be matched with a specific offer, we would like to implement a matching score system that precomputes a matching score between each offer and each request in a specific region.

As this yields some very interesting considerations, we came up with an idea on how to solve this, please see this [document](https://www.overleaf.com/5627945dyzjnw#/18220143/) (German!).

Therefore, implementing this algorithm will probably result in more issues. Please refer them and each commit contributing in this issue.

**Comment by nielsrolf** [comment]
Sorry, i failed to close this autmatically by commit 2e6ebbab81c5df7fbfa0724436ec3abc9765ecb0
